import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import { stocksRouter } from "./stocks.js";
import { analysisRouter } from "./analysis.js";
import { alertsRouter } from "./alerts.js";
import { watchlistRouter } from "./watchlist.js";
import { chatRouter } from "./chat.js";
import { dashboardRouter } from "./dashboard.js";
const router = Router();
router.use(healthRouter);
router.use(authRouter);
router.use("/stocks", stocksRouter);
router.use("/stocks", analysisRouter);
router.use("/alerts", alertsRouter);
router.use("/watchlist", watchlistRouter);
router.use("/chat", chatRouter);
router.use("/dashboard", dashboardRouter);
export default router;